---
version: 1.0.0
slug: stt-fallback
name: stt-fallback
description: Speech-to-text fallback test
url: https://github.com/flubshi/hassio-addons/tree/master/stt-fallback
arch:
  - amd64
  - aarch64
init: false
discovery:
  - wyoming
homeassistant_api: true
options:
  entity_ids: "stt.speech_to_phrase stt.faster_whisper"
  debug_logging: false
schema:
  entity_ids: str
  debug_logging: bool
ports:
  "10300/tcp": null
homeassistant: 2023.11.0
